name: Deploy to Amazon Linux 2023

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
              "mkdir -p ~/app && \
               git -C ~/app clone https://github.com/$GITHUB_REPOSITORY . || \
               (git -C ~/app pull && \
               npm install --production && \
               sudo systemctl restart your-service)"