version: '3'
services:
  web:
    build: .
    command: gunicorn queue_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A queue_service worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
